apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-default-storageclass
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: enforce-single-default-storageclass
      match:
        resources:
          kinds:
            - StorageClass
      validate:
        message: "A default StorageClass already exists. Only one default StorageClass is allowed."
        deny:
          conditions:
            any:
              - key: "{{ request.object.metadata.annotations.\"storageclass.kubernetes.io/is-default-class\" || 'false' }}"
                operator: Equals
                value: "true"
              - key: "{{ request.object.metadata.name }}"
                operator: NotEquals
                value: "robin"
              - key: "{{ kubernetes.storageClasses[?metadata.annotations.\"storageclass.kubernetes.io/is-default-class\" == 'true'] | length(@) }}"
                operator: GreaterThan
                value: 0

    - name: restrict-non-robin-default
      match:
        resources:
          kinds:
            - StorageClass
      validate:
        message: "Only 'robin' can be set as the default StorageClass."
        deny:
          conditions:
            all:
              - key: "{{ request.object.metadata.annotations.\"storageclass.kubernetes.io/is-default-class\" || 'false' }}"
                operator: Equals
                value: "true"
              - key: "{{ request.object.metadata.name }}"
                operator: NotEquals
                value: "robin"

    - name: allow-removal-of-default
      match:
        resources:
          kinds:
            - StorageClass
      preconditions:
        all:
          - key: "{{ request.operation }}"
            operator: Equals
            value: "UPDATE"
      validate:
        message: "Only 'robin' can be set as default, but other storage classes can have the default removed."
        deny:
          conditions:
            all:
              - key: "{{ request.oldObject.metadata.annotations.\"storageclass.kubernetes.io/is-default-class\" || 'false' }}"
                operator: Equals
                value: "true"
              - key: "{{ request.object.metadata.annotations.\"storageclass.kubernetes.io/is-default-class\" || 'false' }}"
                operator: Equals
                value: "true"
              - key: "{{ request.object.metadata.name }}"
                operator: NotEquals
                value: "robin"

