apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: enforce-default-storageclass
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: validate-robin-storageclass
      match:
        resources:
          kinds:
            - StorageClass
      validate:
        message: "The default storage class must be 'robin' with annotation storageclass.kubernetes.io/is-default-class: 'true'."
        deny:
          conditions:
            any:
              - key: "{{ request.object.metadata.annotations.\"storageclass.kubernetes.io/is-default-class\" || 'false' }}"
                operator: NotEquals
                value: "true"
              - key: "{{ request.object.metadata.name }}"
                operator: Equals
                value: "robin"
